name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build cli
      run: make

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./... -v
